### ISSUE TITLE
Add Gacha Result

### ISSUE THREAD

**Issue by saguins** [saguins/saltyGacha#2]
**Gacha Result.** when you quit a Gacha Simulator, you can see how much SSR, SR and R units that you get. (Result in numbers and percentages are acceptable.)

you can see more about Gacha Simulator at [saltyGacha's Hacktoberfest TO-DO list](https://github.com/saguins/saltyGacha)

**Comment by EikeSan** [comment]
Hello @saguins 
I made this issue and some refector in the code, like add a .gitignore,  package structure, cleaner the code. Hope you like it.

#7

**Comment by saguins** [comment]
This issue is solved by **EikeSan**. Thank you for your participation!
