### ISSUE TITLE
Add Gacha Simulator GUI

### ISSUE THREAD

**Issue by saguins** [saguins/saltyGacha#5]
**Gacha Simulator GUI.** More user-friendly and easy to understand.

you can see more about Gacha Simulator at [saltyGacha's Hacktoberfest TO-DO list](https://github.com/saguins/saltyGacha)

**Comment by Immutablevoid** [comment]
Hi, I would like to work on this issue if you can assign it to me

To implement it I will be using[ Java Swing](https://docs.oracle.com/javase/7/docs/api/javax/swing/package-summary.html). If you had a different library/method in mind, I would be happy to try it out.

Here is what I have at the moment using [ Java Swing](https://docs.oracle.com/javase/7/docs/api/javax/swing/package-summary.html):

**Rolling Screen**:
![rolling](https://user-images.githubusercontent.com/30512065/66277636-43526d00-e86f-11e9-82a2-cd640bceaca3.PNG)

**Percentage Screen**:
![image](https://user-images.githubusercontent.com/30512065/66277664-a512d700-e86f-11e9-843c-fb49624820eb.png)

**Quantity Screen**:
![image](https://user-images.githubusercontent.com/30512065/66277675-c1167880-e86f-11e9-8f10-24edb562320e.png)

**List of Characters Screen**:
![image](https://user-images.githubusercontent.com/30512065/66277676-cbd10d80-e86f-11e9-9434-d2a226fac5c8.png)

**Note:** I remove all of the `System.out.println` and change a decent amount of functions to return string values to display for the GUI. 

**For example**, I change these functions below to return string values allowing me to input it into the GUI (These are not all the functions that I had to change, I will give the full list in the pull request):
- huntMenu
- getResultInPercentage
- getResultInQuantity
- getResultListOfCharacters

I tried to create the same 10 template portraits like on the [Overhit Gacha Simulator by GameFever](https://overhit.gamefever.co/gacha/) website, but failed to do so.

If you have any issues or suggestions, I can try my best solving/implementing it.

**Comment by saguins** [comment]
So cool! can't wait to see the full program. 😃

this issue is assign to **ImmutableBox.**
